:verbose: false
:pidfile: ./tmp/sidekiq_for_heavy.pid
:logfile: ./log/sidekiq_for_heavy.log
:concurrency: 6
:queues:
  - mailers
:limits:
  mailers: 10
:schedule:
  test:
    class: SampleWorkerForHeavy
