:verbose: false
:pidfile: ./tmp/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 33
:queues:
  - mailers
  - default
  - low_priority
:limits:
  mailers: 10
  default: 5
  low_priority: 5
:schedule:
  test:
    class: SampleWorker
  switch_to_monthly_plan:
    cron: "0 30 8 1 * *" # 毎月1日 8時40分
    class: SwitchToMonthlyPlanWorker
  
  
